#1
SELECT STUDENT_NAME    '학생 이름',
       STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

#2
SELECT STUDENT_NAME,
       STUDENT_SSN
FROM tb_student
WHERE ABSENCE_YN = 'Y'
ORDER BY DATE(SUBSTRING(STUDENT_SSN, 1, 6)) DESC;

#3
SELECT student_name    학생이름,
       STUDENT_NO      학번,
       STUDENT_ADDRESS '거주지 주소'
FROM tb_student
WHERE SUBSTRING(STUDENT_ADDRESS, 1, 2) IN ('강원', '경기')
AND SUBSTRING(ENTRANCE_DATE, 1, 4) >= 2020
ORDER BY STUDENT_NAME;

#4
SELECT A.PROFESSOR_NAME,
       A.PROFESSOR_SSN
FROM tb_professor A
WHERE A.DEPARTMENT_NO IN (SELECT DEPARTMENT_NO
                          FROM tb_department
                          WHERE DEPARTMENT_NAME = '법학과')
ORDER BY  SUBSTRING(PROFESSOR_SSN, 1, 2);

#5
SELECT STUDENT_NO,
       POINT
FROM tb_grade
WHERE TERM_NO = 202202
AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC,
         STUDENT_NO;

#6
SELECT A.STUDENT_NO,
       A.STUDENT_NAME,
       B.DEPARTMENT_NAME
FROM tb_student A
JOIN tb_department B USING (DEPARTMENT_NO)
ORDER BY A.STUDENT_NAME;

#7
SELECT A.CLASS_NAME,
       DEPARTMENT_NAME
FROM tb_class A
JOIN tb_department B USING (DEPARTMENT_NO);

#8


#9
