#1
SELECT STUDENT_NAME '학생 이름',
       STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

#2
SELECT STUDENT_NAME,
       STUDENT_SSN
FROM tb_student
WHERE ABSENCE_YN = 'Y'
ORDER BY DATE(SUBSTRING(STUDENT_SSN, 1, 6)) DESC;

#3
SELECT